# Generated by Django 4.2.2 on 2023-06-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Argao, Cebu', max_length=100)),
                ('image', models.ImageField(upload_to='beach_images')),
                ('facilities', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Argao, Cebu', max_length=100)),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('amenities', models.TextField()),
                ('room_types', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('image', models.ImageField(upload_to='package_images')),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.beach')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.tourpackage')),
            ],
        ),
    ]
