# Generated by Django 4.2.2 on 2023-06-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0002_roomtype_hotelroomtype_beachroomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_types',
        ),
        migrations.AddField(
            model_name='hotel',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
