# Generated by Django 4.2.2 on 2023-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0003_remove_hotel_description_remove_hotel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='num_reviews',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='hotel_images'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='beach',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='Argao, Cebu', max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='package_images'),
        ),
    ]
