# Generated by Django 4.2.2 on 2023-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0004_remove_hotel_num_reviews_remove_hotel_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='room_types',
            field=models.TextField(default=''),
        ),
    ]
