# Generated by Django 4.2.2 on 2023-06-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0005_beach_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='amenities',
            field=models.TextField(default=''),
        ),
    ]
