# Generated by Django 4.2 on 2023-06-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0011_rename_reservation_hotelandbeachreservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='room_types',
        ),
        migrations.AddField(
            model_name='beach',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotel'),
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotelandbeachreservation',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotelroomtype'),
        ),
    ]
