# Generated by Django 4.2 on 2023-06-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0012_remove_beach_activities_remove_beach_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotel'),
        ),
    ]
