# Generated by Django 4.2 on 2023-06-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0015_hotelandbeachreservation_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beaches_and_hotels.hotel'),
        ),
    ]
