# Generated by Django 4.2 on 2023-06-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches_and_hotels', '0016_alter_beach_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='amenities',
            field=models.TextField(default=''),
        ),
    ]
